version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: spring-batch-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: batch
      MYSQL_USER: ironjin
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
