spring:
  profiles:
    active: local
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch
    username: ironjin
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  batch:
    job:
      #      enabled: false
      name: ${job.name:NONE}

logging:
  level:
    org.springframework.batch: DEBUG
    com.example.batch: DEBUG
